Remove extra references indirect references from photon plugin
Remove extra unneeded packages from shared project, which almost
halves the number of assemblies included with the plugin build.

Had to retarget the photon plugin due to the following error:
`CSC: Error CS1705 : Assembly 'MessagePack' with identity 'MessagePack, Version=2.5.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be' uses 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Memory' with identity 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`

Still appears to work fine on net 4.7.2, plugin is loaded and breakpoints are hit.
JsonConstructor attribute being removed still allows the API to
deserialize ApiGame classes.